### ISSUE TITLE
Use file.path()?

### ISSUE THREAD

**Issue by kbvernon** [bocinsky/paleocar#1]
Hi Kyle. Would it be possible to replace `paste0(out.dir, label, ".models.Rds")` with `file.path(out.dir, paste0(label, ".models.Rds")`? This will make it work better with directory specifications built with `file.path()` and `here()`, which don't include the trailing "/". Right now, if I do `out.dir = here("data")`, the result is "./datalabel.models.Rds" instead of "./data/label.models.Rds". If you think it's worth changing, I'm happy to submit a pull request.

**Comment by bocinsky** [comment]
Done! Pull and let me know that it fixes your issue.

**Comment by kbvernon** [comment]
Works perfect! Thanks, Kyle!
